import { db } from "./db";
import { projects, historyItems, awards, videos, slides, images } from "@shared/schema";
import { sql, eq } from "drizzle-orm";

export async function seedDatabase() {
  console.log("Syncing seed data...");

  const allProjects = [
    {
      title: "Doctor Baz Solo",
      slug: "solo-performer",
      description: "Multi-instrumentalist performer featuring vocals, guitar, piano, and stompbox. Perfect for intimate venues, weddings, and corporate events.",
      fullDescription: "Barry performs as a solo entertainer on vocals, guitar, piano, and stompbox, offering a diverse repertoire perfect for intimate venues, weddings, and corporate events. With decades of experience and a deep musical catalogue spanning blues, jazz, country, and rock, Doctor Baz brings an unforgettable atmosphere to any occasion.",
      imageUrl: "https://barryferrier.com/images/com_osgallery/gal-9/original/johnny-cash-show-cast-plane-singingD9149BA8-BD27-4F5E-DD90-1E0985945371.jpg",
      category: "current",
      featured: true,
      order: 0,
      galleryImages: null,
      youtubeVideos: "[{\"id\": \"TKbfb4rhd40\", \"title\": \"Doctor Baz Solo Performance\"}]",
    },
    {
      title: "Pete C. & Dr. Baz",
      slug: "pete-c-dr-baz",
      description: "Dynamic blues duo with Byron Bay legend Peter Claydon. Authentic blues with powerful vocals and gritty guitar.",
      fullDescription: "A dynamic blues duo with Byron Bay legend Peter Claydon (frontman of The Propellers and The Soul Shakers). The duo features powerful authentic blues with gritty vocals and guitar, performing regularly at iconic Byron Bay venues including the Railway Friendly Bar.",
      imageUrl: null,
      category: "current",
      featured: true,
      order: 1,
      galleryImages: null,
      youtubeVideos: "[]",
    },
    {
      title: "S'uNReel - Collaborations with Ralph Lycett Tyrrell",
      slug: "sunreel",
      description: "Music and theatrical production partnership creating original musicals and genre albums with lyricist Ralph Lycett Tyrrell.",
      fullDescription: "S'uNReel is a music and theatrical production partnership between Dr. Baz (Barry Ferrier) and lyricist/scriptwriter Ralph Lycett Tyrrell. Together they create original musicals and genre albums spanning musical theatre, gypsy jazz, R&B, reggae, country, and pop electronica.\n\nMajor works include \"Fireies the Musical\" (celebrating Australian volunteer firefighters), \"Eve the Musical\" (reimagining the Old Testament from Eve's perspective), and numerous genre albums including \"Dancing on the Edge of the Precipice\" (Gypsy Jazz), \"Irresistible Connection\" (R&B Chill), and \"Famous Last Words\" (Reggae).\n\nBarry provides all music, composition, and production while Ralph contributes lyrics and scripts. All works are released under S'uNReel Productions and available on Bandcamp.",
      imageUrl: "/attached_assets/S'UnReel_Patreon_1770191096220.jpg",
      category: "collaboration",
      featured: true,
      order: 1,
      galleryImages: null,
      youtubeVideos: "[{\"id\": \"VIz6rBoLw7E\", \"title\": \"S'uNReel intro\"}, {\"id\": \"I4DtIleRMRM\", \"title\": \"S'uNReel Award winning music video\"}, {\"id\": \"2gIOufTXDLs\", \"title\": \"S'uNReel fun K-Pop\"}, {\"id\": \"Ys0HNh_lGMM\", \"title\": \"S'uNReel Gothic\"}, {\"id\": \"3fmbN5az-fk\", \"title\": \"S'uNReel & the Existential Crisis\"}, {\"id\": \"1-PirJEHBrM\", \"title\": \"S'uNReel tribute to Brett Whitely\"}]",
    },
    {
      title: "Rayne & Dr Baz",
      slug: "rayne-dr-baz",
      description: "A great new duo performing popular, rock, jazz & blues music. Top shelf entertainment with a big sophisticated sound.",
      fullDescription: "Rayne & Dr Baz perform a wide range of popular, rock, jazz & blues music, creating a big sophisticated sound perfect for entertaining guests at your venue. A class act!\n\nRayne was born and raised in Sydney, entering the entertainment industry at age 4 as a classical ballerina. She performed with the Australian Opera Company alongside Dame Joan Sutherland, and went on to perform with Barry Humphries, Robert Palmer, Peter Allen, Paul Hogan, Meatloaf and Elton John. After years in London working with an independent record label, she released two solo albums before teaming up with Dr Baz.\n\nBarry Ferrier aka Dr Baz is a multi-instrumentalist, singer and multi-award winning songwriter/composer with a long and diverse career beginning with the original production of \"Jesus Christ Superstar\". He has performed at the Byron Blues Fest, Blues on Broadbeach, Tamworth and Airlie Beach Music Festivals, and toured Europe and Ireland.",
      imageUrl: "/attached_assets/RAYNE_&_BAZ_1770349937602.JPG",
      category: "current",
      featured: false,
      order: 2,
      galleryImages: null,
      youtubeVideos: "[]",
    },
    {
      title: "Dr Baz & Rex Carter Duo",
      slug: "dr-baz-rex-carter",
      description: "An energetic duo pairing Barry's multi-instrumental skills with drum master Rex Carter's intricate beats.",
      fullDescription: "An energetic duo pairing Barry's multi-instrumental skills with drum master Rex Carter's intricate Latin beats, funky grooves, and driving rock rhythms. Perfect for venues wanting high energy and musical sophistication in a smaller format.",
      imageUrl: "/attached_assets/Dr_Baz_and_Rex_Carter_Duo_1771549145714.jpg",
      category: "current",
      featured: true,
      order: 2,
      galleryImages: "[\"/attached_assets/Dr_Baz_&_Rex_Carter_1771549136228.jpg\", \"/attached_assets/Dr_Baz_and_Rex_Carter_Duo_1771549145714.jpg\"]",
      youtubeVideos: "[{\"id\": \"WkiITOTnzRw\", \"title\": \"Baz Ferrier & Rex Carter live @ Bangalow Hotel\"}]",
    },
    {
      title: "Between Two Shores: The Mirror Self",
      slug: "between-two-shores",
      description: "A live performance installation co-created by Saya Minami and Barry Ferrier, exploring the psychological and emotional experience of migration through the lens of a Japanese woman becoming bicultural in Australia.",
      fullDescription: null,
      imageUrl: null,
      category: "current",
      featured: false,
      order: 3,
      galleryImages: null,
      youtubeVideos: "[]",
    },
    {
      title: "YarnAI",
      slug: "yarnai",
      description: "AI-driven conversational interface for storytelling and knowledge sharing.",
      fullDescription: "YarnAI represents the next frontier in interactive storytelling, utilizing advanced large language models to create a responsive, engaging narrative experience. The interface is designed to be intuitive, allowing users to 'spin a yarn' through natural conversation.",
      imageUrl: "/attached_assets/IMG_2499_1770239583938.png",
      category: "current",
      featured: true,
      order: 4,
      galleryImages: null,
      youtubeVideos: "[]",
    },
    {
      title: "Bum Fluff and Navel Lint",
      slug: "bumfluff-navellint",
      description: "Test animations for the madcap musical animation series currently in development by S'uNReel Entertainment partners Ralph Lycett Tyrrell and Barry Ferrier (aka Dr Baz).",
      fullDescription: "Madcap musical animation series set in a laundry, featuring quirky characters like Bum Fluff, Navel Lint, Washing Machine (WM), Dizzy the Dryer, and many more. Currently in development by S'uNReel Entertainment.",
      imageUrl: null,
      category: "current",
      featured: false,
      order: 6,
      galleryImages: null,
      youtubeVideos: "[{\"id\": \"iCwuNb8HWtU\", \"title\": \"Bumfluff & Navellint - Track 1\"}, {\"id\": \"VGGRiiwNdts\", \"title\": \"Bumfluff & Navellint - Track 2\"}, {\"id\": \"5XeA0ocky74\", \"title\": \"Bumfluff & Navellint - Track 3\"}]",
    },
    {
      title: "Fireies - The Musical",
      slug: "fireies-the-musical",
      description: "A musical celebration of the values of small town rural Australia — family, community and noble sacrifice when facing adversity.",
      fullDescription: "Fireies - The Musical celebrates the values of small town rural Australia — family, community and noble sacrifice when facing adversity. This original musical production captures the spirit of volunteer firefighters and the communities they protect, weaving together themes of courage, resilience and the bonds that hold rural Australia together.",
      imageUrl: "/attached_assets/Fireies_the_Musical_1770419293451.jpg",
      category: "current",
      featured: false,
      order: 7,
      galleryImages: "[\"/attached_assets/Cliff_at_Bar_2_1770419644021.jpg\",\"/attached_assets/Brad_&_Millie_in_Bar_copy_1770419654282.jpg\",\"/attached_assets/Glenys__1770419673250.jpg\",\"/attached_assets/Weirdo_Midshot_1770419701157.png\"]",
      youtubeVideos: "[{\"id\": \"6JWwiCQ3lOo\", \"title\": \"Firies Intro\"}, {\"id\": \"IACOM7sS6sA\", \"title\": \"Blazing Summer\"}, {\"id\": \"LYvG1ni7i1k\", \"title\": \"Just Another Small Town in Australia\"}, {\"id\": \"d81t7ao3VUM\", \"title\": \"Fireies - The Musical\"}]",
    },
    {
      title: "My Intelligent Health",
      slug: "my-intelligent-health",
      description: "AI-Powered Postoperative Care Management Platform revolutionizing patient outcomes through intelligent automation.",
      fullDescription: "My Intelligent Health is transforming postoperative care through an innovative AI-driven platform that bridges the gap between surgical procedures and full patient recovery. Our solution reduces hospital readmissions by up to 30% while saving clinicians 2+ hours daily through intelligent automation. With enterprise-grade security, multi-region compliance (HIPAA, APP, GDPR), and support for 17 medical specialties across 17 languages, we're positioned to capture a significant share of the $15B+ global post-acute care market.",
      imageUrl: "/attached_assets/lMy_Intelligent_Health_Logo_1770425238192.jpg",
      category: "current",
      featured: false,
      order: 8,
      galleryImages: null,
      youtubeVideos: null,
    },
    {
      title: "Maeve: A First Fleet Saga",
      slug: "maeve-first-fleet-saga",
      description: "An esoteric opera blending European and Aboriginal mysticism, tracing the journey of an Irish healer from conviction to transformation in colonial Australia. A S'uNReel Entertainment production.",
      fullDescription: "Maeve: A First Fleet Saga is an ambitious esoteric opera currently in development by S'uNReel Entertainment partners Barry Ferrier and Ralph Lycett Tyrrell. The work follows Maeve, a young Irish woman with deep connections to elemental spirits, whose gift for natural healing leads to her arrest and transportation to the penal colony of New South Wales aboard the First Fleet. The opera blends European and Aboriginal mysticism into a powerful narrative of freedom, containment, and transformation.",
      imageUrl: null,
      category: "current",
      featured: false,
      order: 8,
      galleryImages: null,
      youtubeVideos: "[]",
    },
    {
      title: "YourSay Video Polling App",
      slug: "yoursay",
      description: "A gamified video polling and engagement platform that transforms passive surveys into addictive experiences with real-time biometric analytics.",
      fullDescription: "YourSay is a state-of-the-art Flutter-based engagement platform that transforms passive surveys into addictive, gamified experiences. Our technology captures real-time emotional reactions to video content using industry-standard worm testing methodology, enhanced with device-universal biometric analytics that require no special hardware.",
      imageUrl: "/attached_assets/yoursay-logo_1770425746697.png",
      category: "current",
      featured: false,
      order: 9,
      galleryImages: null,
      youtubeVideos: null,
    },
    {
      title: "S'uNReel 2026 - GO KOALA!",
      slug: "sunreel-go-koala",
      description: "An animated online episodic series and multiplayer computer game proposal by Ralph Lycett Tyrrell, featuring Ko the koala on an epic journey through the Australian bush. App development and design by Dr Baz.",
      fullDescription: "<p>S'uNReel 2026 - GO KOALA! is an innovative animated episodic series and multiplayer computer game proposal created by Ralph Lycett Tyrrell, with app development and design by Dr Baz.</p><p>Follow Ko the koala on his epic journey through the Australian bush in this unique blend of animated storytelling and interactive gaming. The project combines original character design, environmental storytelling, and multiplayer gameplay mechanics into a compelling cross-platform experience.</p><p>The proposal brings together traditional animation aesthetics with modern game development technology, creating an immersive Australian bush adventure that celebrates native wildlife and landscapes.</p>",
      imageUrl: "/attached_assets/Go_Koala_1770787826297.jpg",
      category: "apps",
      featured: false,
      order: 10,
      galleryImages: null,
      youtubeVideos: null,
    }
  ];

  for (const project of allProjects) {
    await db.insert(projects).values(project).onConflictDoUpdate({
      target: projects.slug,
      set: {
        title: sql`excluded.title`,
        description: sql`excluded.description`,
        fullDescription: sql`excluded.full_description`,
        imageUrl: sql`excluded.image_url`,
        category: sql`excluded.category`,
        featured: sql`excluded.featured`,
        order: sql`excluded."order"`,
        galleryImages: sql`excluded.gallery_images`,
        youtubeVideos: sql`excluded.youtube_videos`,
      },
    });
  }
  console.log(`Synced ${allProjects.length} projects`);

  const allHistory = [
    {
      title: "The Propellers",
      slug: "the-propellers",
      year: "2017-Present",
      description: "Byron Bay-based blues band featuring Pete C., Dr. Baz, Belle Hendrik and Jason Caspen.",
      fullDescription: "Byron Bay based blues band \"The Propellers\" features Pete C. (vocals, guitar), Belle Hendrik (bass), Dr. Baz (aka Barry Ferrier - piano) and Jason Caspen (drums). They regularly perform at the Railway Friendly Bar in Byron Bay and other venues throughout the Northern Rivers region.\n\nThe band delivers powerful blues performances with a repertoire that includes original songs and classic covers from artists like Robert Cray and Tony Joe White. Their energetic live shows showcase the combined talents of four of the region's most accomplished musicians.\n\nDr. Baz was asked to fill in for John Hill in the band, and the connection with frontman Pete C. led to the formation of their popular blues duo \"Pete C. & Dr. Baz\". The Propellers continue to be one of Byron Bay's most respected live blues acts.",
      imageUrl: "https://barryferrier.com/images/com_osgallery/gal-11/original/propellers34D48C019-07A2-5E4C-A504-35D7AC723A1A.jpg",
      category: "bands",
      order: 1,
      galleryImages: "[\"https://barryferrier.com/images/com_osgallery/gal-11/original/propellers34D48C019-07A2-5E4C-A504-35D7AC723A1A.jpg\", \"https://barryferrier.com/images/com_osgallery/gal-11/original/propellers-rails-with-rod0EBC97FE-01FF-2A69-7C2F-FA35ED09C321.jpg\"]",
      youtubeVideos: "[{\"id\": \"5e3mnpV7GBs\", \"title\": \"It All Comes Back - The Propellers live @ The Rails\"}, {\"id\": \"WwpCLH9fTXo\", \"title\": \"A Night at the Rails - The Propellers Live\"}, {\"id\": \"KNNnSmwArQ0\", \"title\": \"Phone Booth - The Propellers, Robert Cray Cover\"}, {\"id\": \"CcHsRdSXrs8\", \"title\": \"Polk Salad Annie - The Propellers\"}, {\"id\": \"di_Yvaj8l5o\", \"title\": \"Willowtree - The Propellers Live\"}, {\"id\": \"fhbQ-MKAQ6U\", \"title\": \"The Propellers Live Performance\"}, {\"id\": \"yz5gYIM3624\", \"title\": \"The Propellers Blues Session\"}]",
    },
    {
      title: "I Hear That Train a-Comin'",
      slug: "johnny-cash-tribute",
      year: "2014-Present",
      description: "Music theatre production based on the life of Johnny Cash featuring Barry as Johnny and Ilona Harker as June Carter.",
      fullDescription: "Country Superstar Johnny Cash was a music industry legend for half a century with an instantly recognisable voice and style. The hit movie \"I Walk the Line\" introduced his dramatic life story and his unmistakeable, tough music to a younger generation of music lovers. Johnny Cash fans now cover three generations.\n\nEven people who might secretly confess to hating Country Music are nevertheless fired up with enthusiasm about his legendary up-tempo hits such as Folsom Prison Blues, Ring of Fire, Get Rhythm, I Walk the Line - there are just so many great and unique songs in the Johnny Cash repertoire.\n\nVocalist & writer Barry Ferrier has brought together a team of talented performers to create an immersive music theatre show based on the Cash Story and interaction between these two gifted and unique music artists, told in the first person with insights into Johnny & the Tennessee Two's wild ride from obscurity to stardom.\n\nBarry has the vocal depth to emulate the unique Johnny Cash sound and the vivacious and versatile Ilona Harker plays the 3 women in Johnny's life as she 'hoots and hollers' her way through this toe-tapping, side slapping mix of great songs and stories.\n\nThe show has been performed to great acclaim at the Gympie Muster, the Alice Springs and Darwin Entertainment Centres, and in Sydney at Panthers Penrith, Souths Sydney Juniors Club, the Blacktown Workers Club and the Camelot Lounge.\n\nFeaturing Barry Ferrier as Johnny Cash and Ilona Harker as June Carter Cash, with authentic rockabilly backing by the Tennessee Two (Marshall Grant played by Slim Pickens and Luther Perkins played by Mark Heazlitt).",
      imageUrl: "https://barryferrier.com/images/johnny-cash-tribute.jpg",
      category: "theatre",
      order: 2,
      galleryImages: "[\"https://barryferrier.com/images/com_osgallery/gal-9/original/johnny-cash-show-cast-plane-singingD9149BA8-BD27-4F5E-DD90-1E0985945371.jpg\", \"https://barryferrier.com/images/com_osgallery/gal-9/original/barry-cash-ilona-carterFBAB5484-358D-6DD3-0489-9B07F5A8004B.jpg\", \"https://barryferrier.com/images/com_osgallery/gal-9/original/johnny-cash-twin-towns-1FB3B5F59-55EE-6AEC-4B61-70D0EF7517C1.jpg\"]",
      youtubeVideos: "[{\"id\": \"mxwF9V4QI_g\", \"title\": \"Johnny Cash Tribute Performance 1\"}, {\"id\": \"Uy8NJBCFnq4\", \"title\": \"Johnny Cash Tribute Performance 2\"}, {\"id\": \"2WVrAG3Po48\", \"title\": \"Johnny Cash Tribute Performance 3\"}, {\"id\": \"7ANOSr_RAK4\", \"title\": \"Johnny Cash Tribute Performance 4\"}, {\"id\": \"rEjm41i-j0g\", \"title\": \"Johnny Cash Tribute Performance 5\"}]",
    },
    {
      title: "Pete C. & Dr. Baz",
      slug: "pete-c-dr-baz",
      year: "2017-Present",
      description: "Blues duo with Peter Claydon performing original and classic blues.",
      fullDescription: "Since Dr. Baz was asked to fill in for John Hill in the Byron Bay soul band \"The Propellers\", Doctor Baz has found a great connection with their frontman and highly respected Byron Bay based blues singer and guitarist Peter Claydon who is known widely as Pete C. (also frontman to the local legends \"The Soul Shakers\").\n\nThey hit it off so well they have gone on to form a unique blues duo and begun performing locally after a debut gig at the legendary Railway Friendly Bar in Byron Bay. With diverse and mature music skills, powerful authentic blues feel, their classy and full bodied gritty sound immediately shone with all the hallmarks of a classic blues outfit.\n\nThey kicked off with a residency at Mullumbimby Ex-Serviceman's Club billed as \"Acoustic Lounge Adventures\" and have performed regularly at local markets, pubs and clubs throughout the Northern Rivers region.",
      imageUrl: "https://barryferrier.com/images/com_osgallery/gal-11/original/baz-pete4E72B963-A8DB-46B3-7FD6-B8CBEB212841.jpg",
      category: "bands",
      order: 3,
      galleryImages: "[\"https://barryferrier.com/images/com_osgallery/gal-11/original/baz-pete4E72B963-A8DB-46B3-7FD6-B8CBEB212841.jpg\", \"https://barryferrier.com/images/com_osgallery/gal-11/original/dr-baz-petec-mullum145A919E-5A26-0DCD-2ACF-B5C2ED29DCC1.jpg\", \"https://barryferrier.com/images/com_osgallery/gal-11/original/pete-c-baz-pianoman-no-text5D1C2A3F-A5E2-E677-89F4-1A1A284C8856.jpg\"]",
      youtubeVideos: "[{\"id\": \"PL-H2G0rnnqqV65KAV_RBYvXynFZ_wm1lM\", \"title\": \"Pete C. & Dr. Baz Playlist\", \"isPlaylist\": true}, {\"id\": \"YQSm3rSjhTk\", \"title\": \"Pete C. & Dr. Baz\"}, {\"id\": \"aze9n2aeJk0\", \"title\": \"Pete C. & Dr. Baz Performance\"}, {\"id\": \"jcrF85mn0UM\", \"title\": \"Pete C. & Dr. Baz Live\"}]",
    },
    {
      title: "Hubcap Stan & the Sidewalk Stompers",
      slug: "hubcap-stan",
      year: "2015-Present",
      description: "Blues, swing & ragtime band featuring handmade instruments and an impressive pedigree of musicians.",
      fullDescription: "Introducing \"Hubcap Stan and the Sidewalk Stompers\" - a giant of a band, fronted by a giant of a man! Hubcap Stan creates the instruments he plays and sings with an authentic gut barrel power!\n\nHubcap Stan & the Sidewalk Stompers are great entertainment for all ages with their diverse repertoire of goodtime blues, swing & ragtime, gypsy jazz and rock 'n' roll that is authentic, cheerful, and awesome fun.\n\nThey bring an astounding array of instruments to the party! Hubcap Stan's fascinating range of hand built guitars, made from timber he salvages and all sorts of surprising things, and his gritty blues harmonica are at the heart of the show. Dr. Baz dazzles with virtuoso skills on electric guitar, piano, accordion, flute and vocals.\n\nStan's had a passion for old country blues & ragtime since the 70s, playing mining camps across Australia. Since 1990 Stan has entertained nationally at trade expos with his unique award winning wood skills show.\n\nRod Coe is one of Australia's best known and most loved double bass & bass guitar players. Rod has played bass for over 50 years, playing Pop, Rock, Blues, Country & Bluegrass across Australia. Long time leader of Slim Dusty's Travelling Country Band, and producer of all Slim's records since '75; Inhouse producer for EMI, incl. debut album by punk legends, The Saints.\n\nAll things that you hit are handled by the highly talented drum master Jason Caspen. We challenge you to resist smiling and dancing!\n\nBig Stan and Doctor Baz also step out as a duo and bring you their eclectic style of goodtime music in a tight two man act, featuring Stan's fascinating hand-made instruments and the rollicking good time sound.",
      imageUrl: "https://barryferrier.com/images/Stan2.jpg",
      category: "bands",
      order: 4,
      galleryImages: "[\"https://barryferrier.com/images/Stan2.jpg\", \"https://barryferrier.com/images/Rod_Coe3.jpg\", \"https://barryferrier.com/images/Jason_Caspen_2.jpg\", \"https://barryferrier.com/images/Hubcap_Stan__Dr._Baz.jpg\"]",
      youtubeVideos: "[{\"id\": \"zDiSNkY_kgY\", \"title\": \"Hubcap Stan & the Sidewalk Stompers Live @ Crabbes Creek Flood Benefit, 2022\"}]",
    },
    {
      title: "Heaven & Hell - Music Theatre",
      slug: "heaven-and-hell",
      year: "2017-Present",
      description: "Music theatre show with Slim Pickens weaving together the Johnny Cash & Roy Orbison stories.",
      fullDescription: "One of rock music's most gifted singers, Roy Orbison grew up in Texas and worked in the oil fields, dreaming of music success. He was gifted with a clear tenor that soared into an angelic falsetto. After a chance meeting with Johnny Cash, he was introduced to Sun Records by this new friend.\n\nJohnny Cash, the Man in Black, was a singer, guitarist and songwriter whose prolific music innovatively mixed country, rock, blues and gospel influences. Together, their lives ran parallel through the highs and lows, personal tragedy, incredible success, disappointments, come-backs and Super Groups.\n\nBoth these wonderful musical talents have left us now, and, in this fantasy show, we meet our two legends in the Waiting Room at the Pearly Gates, where they discover that they each have serious misgivings about how they will be received by Saint Peter.\n\nByron Bay based musicians Barry Ferrier and Slim Pickens met in 2002 at the weekly open mic night at a hotel in Bangalow and immediately forged a friendship and creative partnership that has endured. Barry's ability to emulate the unique deep voice of Johnny Cash is mirrored by Slim's powerful tenor that soars effortlessly to the vocal range made famous by Roy Orbison.\n\nWith both performers strong vocalists and multi instrumentalists, this show can be presented with a cast of just two - with live musical backing (no fake backing tracks). Slim plays double bass to Barry's guitar in the Johnny Cash songs, and Barry plays drums & keyboards to Slim's guitar in the Roy Orbison songs.",
      imageUrl: "https://barryferrier.com/images/johnny-cash-tribute.jpg",
      category: "theatre",
      order: 5,
      galleryImages: "[\"gallery/heaven-hell-poster.jpg\", \"gallery/heaven-hell-2.jpg\", \"gallery/heaven-hell-3.jpg\", \"gallery/heaven-hell-4.jpg\", \"gallery/heaven-hell-5.jpg\"]",
      youtubeVideos: "[{\"id\": \"OdXrczbnh9c\", \"title\": \"Only the Lonely - from Heaven & Hell\"}, {\"id\": \"RNMjS5FSd2g\", \"title\": \"Heaven & Hell plays Tea Gardens Country Club\"}]",
    },
    {
      title: "Rex Carter & Dr. Baz",
      slug: "rex-carter-dr-baz",
      year: "2018-Present",
      description: "Dynamic duo with drum master Rex Carter creating an energetic and diverse sound.",
      fullDescription: "After meeting as members of the high class Byron Bay-based blues band \"The Propellers\", versatile Australian musician Barry Ferrier has now joined forces with drum master Rex Carter to create an exciting new duo for smaller format gigs seeking energetic and uplifting entertainment.\n\nRex brings his brilliant rhythmic feels to further flesh out Dr. Baz's already dynamic solo act, creating a surprisingly big and diverse sound, propelled by Rex's highly creative dance rhythms, intricate latin beats, funky grooves and driving rock feels.\n\nWith decades of top level experience in high quality bands, including extended stints with Australian music legends Jeff St John, and Rory O'Donoghue (of 'Auntie Jack' Fame), Willie Hona of the popular NZ band 'The Herbs', and gigs across Queensland & NSW with the highly acclaimed north coast showband outfit 'The Round Mountain Girls', (plus many more) - Rex adds a whole new dimension to the Dr Baz multi-instrumental show.\n\nAs a duo they produce a dynamic show with a great mix of interesting interpretations of favourite classic songs plus accessible and entertaining Dr. Baz originals.",
      imageUrl: "/attached_assets/Dr_Baz_&_Rex_Carter_1771549136228.jpg",
      category: "bands",
      order: 6,
      galleryImages: "[\"/attached_assets/Dr_Baz_&_Rex_Carter_1771549136228.jpg\", \"/attached_assets/Dr_Baz_and_Rex_Carter_Duo_1771549145714.jpg\"]",
      youtubeVideos: "[{\"id\": \"WkiITOTnzRw\", \"title\": \"Baz Ferrier & Rex Carter live @ Bangalow Hotel\"}]",
    },
    {
      title: "Kobya & Dr. Baz",
      slug: "kobya-dr-baz",
      year: "2010s-Present",
      description: "African beats, world music & classic reggae. A dynamic duo blending Mozambique Marrabenta roots with Byron Bay musical traditions.",
      fullDescription: null,
      imageUrl: "https://byronbaymusic.com.au/images/Kobya--Dr.-Baz.jpg",
      category: "recording",
      order: 7,
      galleryImages: null,
      youtubeVideos: "[{\"id\": \"tiHlfRqb0-E\", \"title\": \"Kobya & Dr. Baz Performance\"}, {\"id\": \"u_VK1oWn0H4\", \"title\": \"Kobya & Dr. Baz Live\"}, {\"id\": \"QQdSJjxnnUM\", \"title\": \"Kobya & Dr. Baz Music\"}, {\"id\": \"dcWJeKrFtRQ\", \"title\": \"Kobya & Dr. Baz Session\"}, {\"id\": \"MbH-NYW7Fls\", \"title\": \"Kobya & Dr. Baz Collaboration\"}]",
    },
    {
      title: "Poco Loco - Norway Tour",
      slug: "poco-loco-norway",
      year: "2007",
      description: "Australian nuevo flamenco trio touring Norway with Billy Miller from The Ferrets, performing 28 shows including Sjyrock Festival.",
      fullDescription: "Poco Loco was an Australian vocal and nuevo flamenco trio that existed for a remarkable single tour of Norway in 2007. The band comprised Barry Ferrier on vocals and lead guitar, Billy Miller (from The Ferrets) on vocals and bass guitar, and Brian Watt on vocals, rhythm guitar and percussion.\n\nAfter rehearsing via mail and a face-to-face session at Billy Miller's Yarraville home in Melbourne, the trio made their debut at Melbourne's Spanish Club before departing for Norway.\n\nThe highlight of the tour was performing at the Sjyrock Music Festival on the remote and stunning island of Vaeroy in the Lofoten Islands, above the Arctic Circle. The band then toured across northern Norway, performing an impressive 28 shows total across the region.\n\nThe Lofoten Islands, known for their dramatic scenery with towering mountains rising from the sea, provided an unforgettable backdrop for this unique musical adventure. The tour represented a reunion of sorts for Barry and Billy Miller, who had previously worked together in Passage and The Ferrets during the 1970s.\n\nThis was a once-in-a-lifetime musical adventure that brought Australian nuevo flamenco sounds to the far reaches of northern Norway.",
      imageUrl: "/attached_assets/amigos9_1770186447021.jpeg",
      category: "touring",
      order: 8,
      galleryImages: "[\"/attached_assets/amigos9_1770186447021.jpeg\", \"/attached_assets/amigos3_1770186447022.jpeg\", \"/attached_assets/2amigos5_1770186447022.jpeg\", \"/attached_assets/2amigos4_1770186447023.jpeg\"]",
      youtubeVideos: "[{\"id\": \"nSlKdtt3_XA\", \"title\": \"Poco Loco - Performance 1\"}, {\"id\": \"MNdCnvTz01Q\", \"title\": \"Poco Loco - Performance 2\"}, {\"id\": \"YENxL3vkW5Q\", \"title\": \"Poco Loco - Performance 3\"}, {\"id\": \"2L6HnCNTzJY\", \"title\": \"Poco Loco - Performance 4\"}, {\"id\": \"WTiqbM4x1ik\", \"title\": \"Poco Loco - Performance 5\"}]",
    },
    {
      title: "Festival Circuit",
      slug: "festival-appearances",
      year: "2000s-Present",
      description: "Byron Bay Bluesfest, Splendour in the Grass (2013, 2018), East Coast Blues Festival (5 times), Blues on Broadbeach (5 times), Gympie Muster, Tamworth.",
      fullDescription: "Doctor Baz has performed at Australia's most prestigious music festivals including Byron Bay Bluesfest, Splendour in the Grass (2013, 2018), East Coast Blues Festival (5 times), Blues on Broadbeach (5 times), Gympie Muster, and Tamworth Country Music Festival. These appearances have cemented his reputation as one of Australia's most versatile and beloved performers.",
      imageUrl: "https://barryferrier.com/images/com_osgallery/gal-1/original/slimbaz-gympieA0CFAE6C-8FB1-F255-5E07-23C74884565D.jpg",
      category: "festivals",
      order: 9,
      galleryImages: null,
      youtubeVideos: null,
    },
    {
      title: "European Tours",
      slug: "european-tours",
      year: "2005-2007",
      description: "60+ gigs in Norway with Slim Pickens & Dr. Baz. London performances, Northern Ireland tour. 2007 Poco Loco tour through Scandinavia.",
      fullDescription: "60+ gigs in Norway with Slim Pickens & Dr. Baz, London performances, Northern Ireland tour. The 2007 Poco Loco tour through Scandinavia brought Australian blues and roots music to appreciative European audiences.",
      imageUrl: "https://barryferrier.com/images/com_osgallery/gal-1/original/baz-slim-vaeroyEB4A320E-79DF-167F-E0F7-34BE941769D2.jpg",
      category: "touring",
      order: 10,
      galleryImages: null,
      youtubeVideos: null,
    },
    {
      title: "Slim Pickens & Dr. Baz",
      slug: "slim-pickens",
      year: "2000s",
      description: "Long-term musical partnership. European tours with 60+ gigs in Norway. Albums 'Cactus' and 'Next Time'. Multiple festival appearances at Gympie Muster and Tamworth.",
      fullDescription: "Long-term musical partnership with Slim Pickens that has produced some of the most memorable performances of Barry's career. European tours with 60+ gigs in Norway, London performances, Northern Ireland tour. Albums 'Cactus' and 'Next Time' showcase their unique blend of blues and roots music. Multiple festival appearances at Gympie Muster and Tamworth Country Music Festival.",
      imageUrl: "https://barryferrier.com/images/com_osgallery/gal-1/original/slim-pickens-drbaz3FEC143C5-8E8F-50B6-D2AF-83CF7FCF871A.jpg",
      category: "touring",
      order: 11,
      galleryImages: null,
      youtubeVideos: null,
    },
    {
      title: "The Kukanarri Show - Tiwi Islands",
      slug: "kukanarri-show",
      year: "1998",
      description: "Community TV show produced for Nguiu, Tiwi Islands addressing youth issues through music and performance.",
      fullDescription: "This project was developed with the Nguiu community, with Barry Ferrier being invited to put together a music/video component and Tracks Dance invited to devise and direct the performance aspects. The performance dealt with the issues identified by the Nguiu community that caused the high youth suicide rate in their community.\n\nTracks directed this movement and visual performance working closely with the community and through the Xavier Catholic Education Centre Nguiu Community. Bill Davis and Barry Ferrier produced a half-hour television show that was presented on the BRACKS community TV system.\n\nThe KUKANARRI SHOW (a traditional word that describes celebrations when the whole community comes together) featured many stories from the community, including its key dreamings and creation stories, its history since colonisation and its current joys.\n\nTracks worked with the children in the local schools and other community groups. The performance took place in an area that was both under cover and outdoors and incorporated large puppets, images and short dances.\n\nProject Stages:\n- Research difficulties and health problems occurring in Nguiu\n- Recruit directors, musical, dance and design personnel\n- Create and rehearse show, write and rehearse anthem, create daily Television shows\n- Perform Kukanarri Show\n- Survey audience and senior students for reactions\n- Cut 20 hours of video into 1 hour documentary\n\nCreative Personnel: Barry Ferrier, Bill Davis, David McMicken and Tim Newth, Brian Wappett\nPerformers: Students from Xavier Community Education Centre, Nguiu community members",
      imageUrl: "https://barryferrier.com/media/k2/galleries/38/1998%20Kukanarri%20Show0.jpg",
      category: "community",
      order: 12,
      galleryImages: "[\"https://barryferrier.com/media/k2/galleries/38/1998%20Kukanarri%20Show0.jpg\", \"https://barryferrier.com/media/k2/galleries/38/1998%20Kukanarri%20Show3.jpg\"]",
      youtubeVideos: "[]",
    },
    {
      title: "Expo 88 Brisbane Animatronic Parades",
      slug: "expo-88",
      year: "1988",
      description: "Composer role at Brisbane's World Expo - one of Australia's most significant cultural events of the 1980s.",
      fullDescription: "Composer role at Brisbane's World Expo 88 - one of Australia's most significant cultural events of the 1980s. This international exposition attracted visitors from around the world and Barry's compositions contributed to the event's artistic success.",
      imageUrl: "https://barryferrier.com/images/com_osgallery/gal-5/original/expo-88-nightparade10B3B2B944-BCB3-8D7D-0B08-A4AA4FF24651.jpg",
      category: "composition",
      order: 13,
      galleryImages: null,
      youtubeVideos: null,
    },
    {
      title: "Dreams & Machines",
      slug: "dreams-and-machines",
      year: "1985",
      description: "Pioneering multimedia electronic music concert at QPAC featuring the Fairlight CMI and Video Instrument.",
      fullDescription: null,
      imageUrl: "/attached_assets/Dreams_&_Machines-Still-from-Giant-Video_Screen_1770158635166.jpg",
      category: "composition",
      order: 14,
      galleryImages: null,
      youtubeVideos: null,
    },
    {
      title: "40 Years in Byron Bay",
      slug: "40-years-byron-bay",
      year: "1980s-Present",
      description: "Pioneer of the local music scene since the early 1980s. Consistent entertainer at leading venues throughout Byron Bay, Gold Coast, and Brisbane.",
      fullDescription: "As a long-time resident of the Byron Bay region, Barry established himself as a pioneer of the local music scene in the early 1980s, becoming a consistent and popular entertainer at all the leading local venues and on the Gold Coast & in Brisbane for over four decades. He performs regularly as a soloist and in an interesting variety of musical combinations, and has had great success as an entertainer for many beautiful Byron Bay weddings.",
      imageUrl: "https://barryferrier.com/images/Doctor-baz/2/Doctor-Baz-Solo.jpg",
      category: "local",
      order: 15,
      galleryImages: null,
      youtubeVideos: null,
    },
    {
      title: "The Camel Man",
      slug: "the-camel-man",
      year: "1980s",
      description: "Owner of four camels, featured in Byron Bay Oleander Festival parade and Sydney publicity stunts with Rodney Gooch.",
      fullDescription: "Barry Ferrier once was the proud owner of four camels - Bunji (the bull camel), Isabelle, Shanti, and one other. He became known as \"The Camel Man\" during the early 1980s in Byron Bay.\n\n<img src=\"/objects/uploads/9aca1d40-ca5e-4162-b902-09214b7f9aff\" alt=\"Barry Ferrier - The Camel Man newspaper clipping\" style=\"max-width:100%; border-radius:8px; margin:1rem 0;\" />\n\nIn 1981, Barry was invited to ride his camels up Jonson Street as part of the Byron Bay Oleander Festival Parade. Mounted on Bunji with Robyn Bekker riding Isabelle, the procession was going well until the fire engine at the head of the parade let off its siren. The camels took fright and bolted onto the footpath, galloping down the sidewalk as shocked onlookers scattered in pandemonium. Barry had to crouch down and actually bumped his head on a shop awning.\n\nIn 1984, Barry was hired through an advertising agency to bring the camel team to Sydney for a publicity stunt promoting the opening of the Shell Building in North Sydney. An eccentric crew crossed Sydney Harbour on a barge with two large blue and gold cut-out palm trees, half a tonne of white sand, the camels in splendid regalia, belly dancers, and Barry and his friend Rodney Gooch dressed as fugitives from the Arabian Nights. They made the Channel 9 news when they were drenched by torrential rain.\n\nBarry first met the inimitable Rodney Gooch while performing at a restaurant called The Palms in Bangalow. Rodney had made an epic year-long journey from Alice Springs to Byron Bay with four camels and a dog, crossing the Simpson Desert unassisted. When Rodney was over his camel adventure, Barry became the guardian of those foot-sore camels, giving camel-rides at local markets and being booked for children's parties.\n\nRodney Gooch went on to be influential in establishing the first aboriginal recording studio and assisted the earliest contemporary aboriginal bands to be recorded. He encouraged artists of the Utopia community, including the late Emily Kame Kngwarreye, now regarded as one of Australia's most significant artists.",
      imageUrl: "https://barryferrier.com/images/com_osgallery/gal-4/original/camelsF1EC2409-01AC-5FCB-2DF6-BA726ABFF01E.jpg",
      category: "festivals",
      order: 16,
      galleryImages: "[\"https://barryferrier.com/images/com_osgallery/gal-4/original/camelsF1EC2409-01AC-5FCB-2DF6-BA726ABFF01E.jpg\", \"https://barryferrier.com/images/com_osgallery/gal-4/original/oleander-festivalA52FDE46-E282-8F6E-0AA8-8756CE4559CF.jpg\", \"https://barryferrier.com/images/com_osgallery/gal-4/original/baz-camelman-2D7846B17-B1FE-7732-298D-B87CCA9A6803.jpg\", \"https://barryferrier.com/images/com_osgallery/gal-4/original/the-camel-team2B94B4715-080A-D3B2-F2BE-7D14E1A8970D.jpg\"]",
      youtubeVideos: "[{\"id\":\"aNmq7lIOIIM\",\"title\":\"The Camel Man\"}]",
    },
    {
      title: "Three Legends of Kra",
      slug: "three-legends-kra",
      year: "1980s",
      description: "Production with Robyn Archer featuring women heroes. Designed by Nigel Triffett, starred Diane Cilento. Barry wrote music for and conducted the Brisbane Youth Orchestra.",
      fullDescription: "A prestigious production with the legendary Robyn Archer featuring women heroes. Designed by Nigel Triffett and starred the acclaimed actress Diane Cilento. Barry wrote music for and conducted the Brisbane Youth Orchestra - a challenging and rewarding artistic collaboration.",
      imageUrl: "https://barryferrier.com/images/com_osgallery/gal-6/original/3-legends-of-kra-set9451277A-9BC6-5805-B7D2-B2027F124387.jpeg",
      category: "composition",
      order: 17,
      galleryImages: null,
      youtubeVideos: null,
    },
    {
      title: "Eartha Kitt - Australian Tour",
      slug: "eartha-kitt",
      year: "1980s",
      description: "Band leader and tour with the legendary diva Eartha Kitt - a career highlight working with one of entertainment's greatest stars.",
      fullDescription: "Band leader and tour with the legendary diva Eartha Kitt - a career highlight working with one of entertainment's greatest and most iconic stars. The experience of touring with such a consummate professional was invaluable and remains one of Barry's most cherished musical memories.",
      imageUrl: "/attached_assets/IMG_4064_1770241128581.jpeg",
      category: "touring",
      order: 18,
      galleryImages: "[{\"url\": \"IMG_4064_1770241128581.jpeg\", \"caption\": \"Eartha Kitt Live in Australia\"}, {\"url\": \"John-Hoffman_1770240806383.png\", \"caption\": \"John Hoffman - Trumpet\"}, {\"url\": \"warwick_alder_1770240836123.jpeg\", \"caption\": \"Warwick Alder - Trumpet\"}, {\"url\": \"bob_birtles_1770240918817.jpeg\", \"caption\": \"Bob Birtles - Saxophone\"}, {\"url\": \"Eartha_Kitt_Catwoman_Batman_1967_1770240954073.jpeg\", \"caption\": \"Eartha Kitt as Catwoman (1967)\"}]",
      youtubeVideos: "[{\"id\": \"Ibg89qhBsxM\", \"title\": \"Eartha Kitt - I Want to Be Evil\"}, {\"id\": \"waBFnShAnlA\", \"title\": \"Eartha Kitt - Old Fashioned Girl\"}, {\"id\": \"XdFP2dkvXnY\", \"title\": \"Eartha Kitt - Where is My Man\"}, {\"id\": \"b_iM4oWRK70\", \"title\": \"Eartha Kitt - Santa Baby\"}]",
    },
    {
      title: "Giant Steps - 80s Indie Rock",
      slug: "giant-steps",
      year: "1980s",
      description: "'Maybe the best band I ever had the privilege of working with.' Indie rock band with innovative music video production.",
      fullDescription: "'Maybe the best band I ever had the privilege of working with.' Giant Steps was an indie rock band with innovative music video production that pushed creative boundaries. The band represented a period of artistic experimentation and musical growth.",
      imageUrl: "/attached_assets/Giant-Steps2_1770157343581.jpg",
      category: "bands",
      order: 19,
      galleryImages: null,
      youtubeVideos: null,
    },
    {
      title: "Dr. Baz Gig Poster Archive",
      slug: "gig-poster-archive",
      year: "1980s-Present",
      description: "Collection of 40+ promotional posters and artwork created by Dr. Baz throughout his music career. PhD-level multimedia design meets rock & roll.",
      fullDescription: null,
      imageUrl: "https://byronbaymusic.com.au/images/com_osgallery/gal-13/original/doctorbaz-in-heaven3C75187B-2FAE-37C8-A4A9-7C6595B613FD.jpg",
      category: "design",
      order: 20,
      galleryImages: null,
      youtubeVideos: null,
    },
    {
      title: "Goodnight World - The Musical",
      slug: "goodnight-world",
      year: "1984",
      description: "Musical comedy of terrors co-written with Gerald Frape, staged at La Boite Theatre Brisbane.",
      fullDescription: "In 1983 Barry co-wrote (with journalist, social issue campaign specialist and media lecturer Gerald Frape) the musical comedy of terrors \"Goodnight World\", which enjoyed a 4 week season at Brisbane's historic La Boite Theatre in October 1984 (a suitably Orwellian year).\n\nDirected by the talented award winning writer/director Mary Hickson and with a cast of 16 young actors, the show was set in a television studio on the eve of Armageddon. \"Goodnight World\" is a current affairs program that goes to air at midnight, and tonight the show is dedicated to Doomsday Theories - however, as fate would have it, Atomic Annihilation swept the world. The cast is trapped in the underground tv studio - and the show must go on.\n\nBarry Ferrier played Professor E.H. Bagwash (complete with bad Russian accent) who was there to demonstrate the future of humanity - an android.\n\n\"Is the real purpose of the human race to breed a race of perfect Androids - a being that doesn't hate, that makes rational decisions not influenced by greed and xenophobia, an intelligent creature that doesn't destroy its own environment?\"\n\nThe Android was played by Tracey Tainsh (known for films Frenchman's Farm, The Power, the Passion and Bootleg). Rebecca Frith, another outstanding Australian actress known for Love Serenade and Me Myself I, and NIDA graduate Jeremy Godwin also appeared in the cast. Prominent Brisbane multi instrumentalist Donald Hall was band leader and vocal coach.\n\nThe show received a rave review from The Australian celebrating its pop melodies and recommending it move to other capitol cities.",
      imageUrl: "/attached_assets/IMG_0087_1770178231460.png",
      category: "theatre",
      order: 21,
      galleryImages: "[\"/attached_assets/IMG_0087_1770178231460.png\", \"/attached_assets/1984-goodnight-world-pm02_800-fit_1770179412063.jpeg\", \"https://barryferrier.com/images/com_osgallery/gal-7/original/la-boite-1-oct-20028DAC8BE4-8E62-2F68-7AC0-7BCC543D4516.jpg\"]",
      youtubeVideos: "[{\"id\": \"qpMHgkyXntY\", \"title\": \"Android - from Goodnight World composed by Barry Ferrier\"}]",
    },
    {
      title: "Beach",
      slug: "beach-1982",
      year: "1982",
      description: "Avant-garde theatrical experience with Paul Rainsford Towner at Rochedale Theatre.",
      fullDescription: "In 1982 Barry collaborated with brilliant Lismore born artist Paul 'Rainsford' Towner in staging the (for the time) outrageous avant garde theatrical experience 'Beach' at the unsuspecting Rochedale Theatre in Goonellabah. Barry had the fascinating opportunity of creating the music score and taking a lead role.\n\nA ton of white sand was deposited on the historic little stage. It only seats 88 so despite pushing the boundaries of experimental theatre - it was a stunningly atmospheric, dreamlike mime and mixed media piece, and a long way from an amateur musical - we did get enough curious punters in the door to make for an exciting audience buzz.\n\nA ton of white sand on the stage made for the freedom of a very physical performance - you could dive like you were at the archetypal beach that was evoked in imagery and sound. Rainsford's imagination is vivid, challenging and erotic, and strangely beautiful.\n\nThere is nothing like the atmosphere of idealism and excitement in being part of a small theatre company attempting the impossible.\n\nDancer Tanya Waters starred as \"Innocence\" in the ground breaking surrealist theatre experience. Innocence was completely buried in the sand (it took incredible discipline on her behalf) and later would stun unexpecting audiences by emerging in a slo-mo mime / ritual birth.\n\nRainsford has gone on to international respect for his work with the Melbourne based Chapel of Change experimental theatre group and recently directed the stunning hi-tech 3D / virtual reality coverage of the Korean Winter Olympic Games.",
      imageUrl: "https://barryferrier.com/images/Tanya_Waters_as_Innocence_in_Beach.jpg",
      category: "theatre",
      order: 22,
      galleryImages: "[\"https://barryferrier.com/images/Tanya_Waters_as_Innocence_in_Beach.jpg\", \"https://barryferrier.com/images/Beach_Review.jpg\", \"https://barryferrier.com/images/Beach_Curtain_Call.jpg\", \"/attached_assets/Barry_Ferrier_Beach_Rochedale_Theatre_Lismore_1770593631286.jpg\", \"/attached_assets/Beach_Rochedale_Theatre_Lismore_1770593631286.jpg\"]",
      youtubeVideos: "[]",
    },
    {
      title: "Lindsay Kemp Company",
      slug: "lindsay-kemp",
      year: "Late 1970s",
      description: "Composer for the world-famous mime company. Composed music for 'Salome' at London's Roundhouse - an 18-month sell-out season.",
      fullDescription: "Composer for the world-famous Lindsay Kemp Mime Company, performing in their productions of 'Flowers' in Melbourne. Barry composed the music for Kemp's production of Oscar Wilde's 'Salome' - an 18-month sell-out season at London's prestigious Roundhouse theatre. This collaboration represented a high point of artistic achievement working with one of the world's most innovative theatrical visionaries.",
      imageUrl: "https://barryferrier.com/images/com_osgallery/gal-3/original/lindsay-kemp-flowers-salome223091110-ECF0-6FC1-FF75-2EC50D6C3FE5.jpg",
      category: "theatre",
      order: 23,
      galleryImages: null,
      youtubeVideos: null,
    },
    {
      title: "The Astounding Optimissimos",
      slug: "astounding-optimissimos",
      year: "1977",
      description: "Surrealist musical 'Paradise: Depression Style' at Melbourne's legendary Pram Factory, directed by Jean Pierre Mignon.",
      fullDescription: null,
      imageUrl: "/attached_assets/Astounding_Optimissimos_Poster_1770156304275.jpg",
      category: "theatre",
      order: 24,
      galleryImages: null,
      youtubeVideos: null,
    },
    {
      title: "Lindon Ferrier & RCA Records",
      slug: "lindon-ferrier",
      year: "1970s-80s",
      description: "Music duo with Cammie Lindon. ABC's 'Countdown' appearance, RCA recording artist. Opened for guitar maestro Ry Cooder at Palais Theatre, Melbourne.",
      fullDescription: "Music duo with Cammie Lindon that achieved national recognition. Appeared on ABC's legendary 'Countdown' program, becoming RCA recording artists. One of the career highlights was opening for guitar maestro Ry Cooder at Palais Theatre, Melbourne - an unforgettable experience performing alongside such a legend.",
      imageUrl: "https://barryferrier.com/media/k2/galleries/8/Lindon%20Ferrier%20Press.jpg",
      category: "recording",
      order: 25,
      galleryImages: "[\"gallery/lindon-ferrier.jpg\", \"/attached_assets/Lindon_Ferrier_1770593791870.png\"]",
      youtubeVideos: null,
    },
    {
      title: "Africa: The Savage Musical",
      slug: "africa-savage-musical",
      year: "1970s",
      description: "Original cast member of Steve J. Spears' politically charged satirical musical about apartheid and Indigenous rights.",
      fullDescription: "After performing in Jesus Christ Superstar, Barry Ferrier joined the original cast of Africa: The Savage Musical, a politically charged theatrical work written by Steve J. Spears. The show drew sharp parallels between South African apartheid and the treatment of Indigenous Australians, using catchy songs, slapstick, and physical satire to deliver its message.\n\nBarry's theatrical funk rock band Skeleton Crew (featuring Peter Leighton on drums, Chris Doyle on bass, and keyboardist Andrew Thomas Wilson) later performed in a revival season at the VCA Theatre in Melbourne. At that time, Skeleton Crew was popular on the Sydney music scene and had even been supported by a young Icehouse at a NSW Uni Roundhouse concert.\n\nAfter the show, Barry worked with cast members Rod Freeman Smith and Glenda Lum on a rock cabaret called \"Kabaratz\" at the Flying Trapeze Theatre Restaurant in Melbourne.\n\nThe musical combined political commentary with highly melodic songs and physical theater, critiquing both apartheid and Indigenous Australian issues through satire and funk/rock sensibility.",
      imageUrl: "/attached_assets/IMG_2498_1770238858471.jpeg",
      category: "theatre",
      order: 26,
      galleryImages: "[\"/attached_assets/IMG_2498_1770238858471.jpeg\", \"/attached_assets/IMG_2491_1770238339953.png\", \"/attached_assets/IMG_2497_1770238367538.png\", \"/attached_assets/IMG_2492_1770238401443.png\", \"/attached_assets/IMG_2488_1770238432923.png\", \"/attached_assets/IMG_2489_1770238487284.png\", \"/attached_assets/IMG_2494_1770238568152.png\", \"/attached_assets/IMG_2490_1770238609307.png\", \"/attached_assets/IMG_2496_1770238646055.png\", \"/attached_assets/IMG_2495_1770238676796.png\", \"/attached_assets/IMG_2493_1770238703259.jpeg\"]",
      youtubeVideos: "[]",
    },
    {
      title: "A Thousand Bands",
      slug: "a-thousand-bands",
      year: "1970s-Present",
      description: "50 years of musical collaborations. From The Shadows to Cold Chisel support, Jeff St. John, Rusty Miller, and countless bands across the Australian music scene.",
      fullDescription: null,
      imageUrl: "https://barryferrier.com/images/42BC9072-6F9F-4C8D-9D91-CC3A7CE9B600.jpeg",
      category: "recording",
      order: 27,
      galleryImages: null,
      youtubeVideos: "[{\"id\": \"PL-H2G0rnnqqVtUUwJL1AyhLAWIT2ygSwT\", \"title\": \"A Thousand Bands Playlist\", \"isPlaylist\": true}, {\"id\": \"KgJrUuAp-gA\", \"title\": \"A Thousand Bands Performance\"}, {\"id\": \"-9zr75Wrw5E\", \"title\": \"A Thousand Bands\"}]",
    },
    {
      title: "Joseph & the Amazing Technicolour Dreamcoat",
      slug: "joseph-dreamcoat",
      year: "1970s",
      description: "Performed at Seymour Centre, Sydney with Mark Holden, directed by internationally acclaimed Rufus Collins.",
      fullDescription: "Performed at the prestigious Seymour Centre, Sydney with Mark Holden, directed by the internationally acclaimed Rufus Collins. This Tim Rice and Andrew Lloyd Webber musical showcased Barry's versatility as a performer in major theatrical productions.",
      imageUrl: "https://barryferrier.com/images/com_osgallery/gal-8/original/joseph-the-technicolour-dreamcoatB6373F73-856B-178E-7C64-15BB1A1E8B89.jpg",
      category: "theatre",
      order: 28,
      galleryImages: null,
      youtubeVideos: null,
    },
    {
      title: "Musical Theatre Works",
      slug: "musical-theatre",
      year: "1970s-1990s",
      description: "Original musicals and jazz opera compositions with John Paul Young, Reg Livermore, Colin Hay. Recorded at Alberts Productions with Ted Albert.",
      fullDescription: null,
      imageUrl: "https://barryferrier.com/media/k2/galleries/21/Boy%20Who%20Dared%20to%20Dream%202.jpg",
      category: "composition",
      order: 29,
      galleryImages: null,
      youtubeVideos: "[{\"id\": \"bADDmMFs9AE\", \"title\": \"Musical Theatre Works Performance\"}, {\"id\": \"Z27qLYgemeI\", \"title\": \"Musical Theatre Works Live\"}, {\"id\": \"nVPJyklXOXQ\", \"title\": \"Musical Theatre Works Production\"}, {\"id\": \"URW8XYjUkYM\", \"title\": \"Musical Theatre Works Recording\"}]",
    },
    {
      title: "Academic Career & PhD",
      slug: "academic-career",
      year: "1974-2007",
      description: "Extensive academic career culminating in PhD in Multimedia from Southern Cross University.",
      fullDescription: "Barry graduated with a Bachelor of Arts from the University of Sydney majoring in Psychology in 1974. He completed a Diploma of Music Composition under Dr. James Penberthy and Richard Mills at Southern Cross University in 1984. He began lecturing in Music Business and tutoring in guitar at Southern Cross University in the mid eighties and graduated with Bachelor of Letters (Honours) from Deakin University in 1987.\n\nIn the 90s Barry Ferrier was appointed Assistant Professor of Multimedia at Bond University on Queensland's Gold Coast, where he also lectured in the School of Film and TV in Video Production and Music Video. He has held lecturing positions in multimedia and music at Griffith University at Southport, Southern Cross University in Lismore and for three years at Central Queensland University. He has also taught multimedia and graphic design at Kingscliff TAFE for five years and the School of Audio Engineering in Byron Bay.\n\nHe began studying for his Doctor of Philosophy in music at Southern Cross University but two years work on his thesis was destroyed in a house fire in 1994. He later began a new PhD project focusing on the emerging multimedia art technology which he completed through Southern Cross University in 2007.\n\nPhD Thesis: \"Multimedia as Meta-Art: The processes and aesthetics of interactive digital art. A folio of Original Multimedia and Supporting Documentation\"\n\nThe creative work comprised a large scale experimental video animation with synchronized audio/music track entitled \"Take Your Space Now\", and an experimental interactive CD-ROM entitled \"the Machine\".\n\nAcademic Qualifications:\n- Bachelor of Arts (Psychology), University of Sydney, 1974\n- Diploma of Music Composition, Southern Cross University, 1984\n- Bachelor of Letters (Honours), Deakin University, 1987\n- Doctor of Philosophy (Multimedia), Southern Cross University, 2007",
      imageUrl: "https://barryferrier.com/media/k2/galleries/27/p1a5vk3kp9id3se66qmoi01bj4.jpg",
      category: "academic",
      order: 30,
      galleryImages: "[\"https://barryferrier.com/media/k2/galleries/27/p1a5vk3kp9id3se66qmoi01bj4.jpg\", \"https://barryferrier.com/media/k2/galleries/27/p1a5vk3p4t1p3iljq2djd5l9jh5.jpg\", \"https://barryferrier.com/media/k2/galleries/27/p1a5vk423cu8d1okm1i1e7471ac26.jpg\"]",
      youtubeVideos: "[]",
    },
    {
      title: "Jesus Christ Superstar",
      slug: "jesus-christ-superstar",
      year: "Early 1970s",
      description: "Original Harry M. Miller production at Capitol Theatre, Sydney and Palais Theatre, Melbourne. 2 years, 8 shows per week alongside Jon English, Marcia Hines, John Paul Young, and Michael Caton.",
      fullDescription: "Barry gained early recognition in music theatre, appearing in the original Harry M. Miller production at Capitol Theatre, Sydney and Palais Theatre, Melbourne. Over 2 years performing 8 shows per week alongside legends Jon English, Marcia Hines, John Paul Young, and Michael Caton. This production was a defining moment in Australian theatre history.",
      imageUrl: "https://barryferrier.com/images/com_osgallery/gal-2/original/jon-english-jcs5E212F54-2271-1826-C6D5-D4F70A343318.jpg",
      category: "theatre",
      order: 31,
      galleryImages: null,
      youtubeVideos: null,
    },
    {
      title: "Working with Jeff St John",
      slug: "jeff-st-john",
      year: "1970s",
      description: "Barry Ferrier worked with Australian rock legend Jeff St John during the mid-1970s, one of Australia's finest rock vocalists known for hits like \"Big Time Operator\" and \"Teach Me How to Fly\".",
      fullDescription: null,
      imageUrl: "/attached_assets/jeff_st_john_1770242219265.jpeg",
      category: "touring",
      order: 31,
      galleryImages: null,
      youtubeVideos: null,
    }
  ];

  for (const item of allHistory) {
    await db.insert(historyItems).values(item).onConflictDoUpdate({
      target: historyItems.slug,
      set: {
        title: sql`excluded.title`,
        year: sql`excluded.year`,
        description: sql`excluded.description`,
        fullDescription: sql`excluded.full_description`,
        imageUrl: sql`excluded.image_url`,
        category: sql`excluded.category`,
        order: sql`excluded."order"`,
        galleryImages: sql`excluded.gallery_images`,
        youtubeVideos: sql`excluded.youtube_videos`,
      },
    });
  }
  console.log(`Synced ${allHistory.length} history items`);

  const allAwards = [
    { title: "Dolphin Award - Best Blues Artist", description: "N.C.E.I.A. recognition for outstanding blues performance and contribution to the Northern NSW music scene.", year: "Multiple Years", category: "music", order: 0 },
    { title: "Dolphin Award - Best Music Video", description: "N.C.E.I.A. recognition for outstanding achievement in music video production.", year: "2008", category: "music", order: 0 },
    { title: "Golden Reel Award", description: "Award for community radio excellence. A radio series produced in collaboration with Bill Davis, broadcast on C.A.A.M.A. (Central Australian Aboriginal Media Association).", year: "2000s", category: "composition", order: 0 },
    { title: "A.S.E.A. Award for Excellence in the Arts", description: "Australian Society for Excellence in the Arts award for the children's theatre production 'Solomon and the Big Cat', composed during tenure as resident composer at QPAC, Brisbane.", year: "Mid-1980s", category: "theatre", order: 0 },
    { title: "Dolphin Award - Best Jazz Artist", description: "Recognition of excellence in jazz performance across the Northern NSW entertainment industry.", year: "Multiple Years", category: "music", order: 1 },
    { title: "Multicultural Award - Green Tea", description: "Department of Ethnic Affairs award for the culturally sensitive and artistically significant score for 'Green Tea'.", year: "1990s", category: "composition", order: 2 },
    { title: "PhD in Multimedia Design", description: "Doctoral degree from Southern Cross University, exploring concepts of meta-art and synthesis of the arts through multimedia technology.", year: "2004", category: "academic", order: 3 },
    { title: "Bond University Professorship", description: "Appointed Assistant Professor of Multimedia at the prestigious Bond University, Gold Coast.", year: "2000s", category: "academic", order: 4 },
    { title: "Byron Bay Bluesfest Featured Artist", description: "Selected performer at Australia's premier blues and roots festival.", year: "2012", category: "festivals", order: 5 },
    { title: "Splendour in the Grass", description: "Featured performer at Australia's largest contemporary music festival, appearing in 2013 and 2018.", year: "2013, 2018", category: "festivals", order: 6 },
    { title: "Salome - 18 Month Sell-Out", description: "Composer for Lindsay Kemp Company's production of Oscar Wilde's Salome at London's Roundhouse - an outstanding 18-month sell-out run.", year: "Late 1970s", category: "theatre", order: 7 },
    { title: "27 International Film Awards", description: "In just two years, Barry Ferrier has won 27 international film festival awards across 19 videos on three continents, with several films winning multiple awards for his AI-generated experimental films including Entombed and Brushstrokes in Time.", year: "2024-2026", category: "film", order: 12 }
  ];

  const existingAwards = await db.select().from(awards);
  const existingAwardMap = new Map(existingAwards.map(a => [a.title, a]));
  for (const award of allAwards) {
    const existing = existingAwardMap.get(award.title);
    if (!existing) {
      await db.insert(awards).values(award);
    } else if (existing.description !== award.description || existing.year !== award.year || existing.category !== award.category) {
      await db.update(awards).set({ description: award.description, year: award.year, category: award.category, order: award.order }).where(eq(awards.title, award.title));
    }
  }
  console.log("Awards synced");

  const allVideos = [
    { title: "The City", description: "Experience Barry's electronic music composition combining multimedia art and experimental sound. A pioneer of techno music in Australia.", youtubeId: "BmfO-K4cyvk", category: "ai-video", featured: true, order: 0 },
    { title: "Johnny Cash Tribute", description: "Highlights from 'I Hear That Train a-Comin' show featuring Barry's powerful interpretation.", youtubeId: "mxwF9V4QI_g", category: "johnny-cash", featured: false, order: 2 },
    { title: "Angelina", description: "\"Angelina\" - Latin jazz guitar instrumental by Barry Ferrier.", youtubeId: "rf4LJXzW4J0", category: "instrumental", featured: false, order: 3 },
    { title: "Johnny Cash Tribute Live", description: null, youtubeId: "Uy8NJBCFnq4", category: "johnny-cash", featured: false, order: 3 },
    { title: "Much More - Giant Steps", description: "In the 80s I formed a great indie rock band called \"Giant Steps\" - maybe the best band I ever had the privilege of working with. Featuring: Lisa Spence (Vocal), Barry Ferrier (Guitar), Jen Anderson (Violin), Gordon Heazelwood (Drums), Richard Rummery (Keyboards), Paul Rainsford Towner (Vision Mix). © Barry Ferrier", youtubeId: "videoseries?list=PL-H2G0rnnqqXoNvySLfcfyFUoeVO7AuBC", category: "giant-steps", featured: false, order: 4 },
    { title: "Break the Ice - Giant Steps Live", description: null, youtubeId: "FT2kmiMYInA", category: "giant-steps", featured: false, order: 5 },
    { title: "Missionary Man - Giant Steps", description: "Eurythmics cover performed by Giant Steps at Lennox Head Beach in the mid 80s.", youtubeId: "8PwY-Qo7_oI", category: "giant-steps", featured: false, order: 6 },
    { title: "Making of Bureaucracy - Documentary", description: "Home-grown documentary of the ambitious one-take music video for \"Bureaucracy\" - filmed at a specially built set with 6 separate rooms at the Alstonville chicken farm.", youtubeId: "r6-l-8WFvoA", category: "giant-steps", featured: false, order: 7 },
    { title: "Mihn Mihn Lights", description: "Early experimental electronic soundtrack composed by Barry Ferrier.", youtubeId: "0w5Bl2CrTc4", category: "electronic", featured: false, order: 20 },
    { title: "Fantasy in C Minor - Classical Guitar", description: "\"Fantasy in C Minor\" for Classical Guitar. Original composition by Barry Ferrier.", youtubeId: "5FF0Ac_YIPE", category: "instrumental", featured: false, order: 20 },
    { title: "Armageddon Blues - Dr Baz", description: null, youtubeId: "hduvZdhQyiA", category: "blues-roots", featured: false, order: 20 },
    { title: "Crazy World - Guitar Instrumental", description: "\"Crazy World\" - Guitar Instrumental. Original composition by Barry Ferrier.", youtubeId: "xjBfDQ7KlwA", category: "instrumental", featured: false, order: 21 },
    { title: "Bananaland", description: "Composed by Barry Ferrier on the Fairlight CMI IIX.", youtubeId: "-kWsL1oJdFk", category: "electronic", featured: false, order: 21 },
    { title: "Voodoo Rhythm", description: null, youtubeId: "NoTeLaKa4aM", category: "blues-roots", featured: false, order: 21 },
    { title: "Chrysalis", description: "Early experimental electronica by composer Barry Ferrier (Fairlight CMI IIX). Soundtrack for Vision Dance ensemble choreographed by Ginny Bradley.", youtubeId: "i-sNphrfEsM", category: "electronic", featured: false, order: 22 },
    { title: "Sea of Glass - Guitar Instrumental", description: "\"Sea of Glass\" - Guitar Instrumental. Original composition by Barry Ferrier.", youtubeId: "EyOIvpqbFh4", category: "instrumental", featured: false, order: 22 },
    { title: "Mean Talking Blues - Dr Baz sings Woody Guthrie", description: null, youtubeId: "z563dHQnbac", category: "blues-roots", featured: false, order: 22 },
    { title: "Disco-Lobotomy", description: null, youtubeId: "xtJ5RWHOgws", category: "blues-roots", featured: false, order: 23 },
    { title: "On the Launchpad", description: "Fairlight CMI IIX composition by Barry Ferrier.", youtubeId: "xvELi4M8_50", category: "electronic", featured: false, order: 23 },
    { title: "Saxaphone Sam", description: "Early experimental electronic soundtrack by Barry Ferrier (Fairlight CMI IIX).", youtubeId: "34YFJOXtEII", category: "electronic", featured: false, order: 24 },
    { title: "Neurocratic Pulse", description: "Early experimental electronica by composer Barry Ferrier on Fairlight CMI IIX.", youtubeId: "k7n9PJBa7TY", category: "electronic", featured: false, order: 25 },
    { title: "Android", description: "From the rock musical \"Goodnight World\" composed by Barry Ferrier. Early Pop Electronica.", youtubeId: "qpMHgkyXntY", category: "electronic", featured: false, order: 26 },
    { title: "Revenge of the Neo-Luddites", description: "Early experimental electronica by Barry Ferrier.", youtubeId: "57-RtqxvA8E", category: "electronic", featured: false, order: 27 },
    { title: "Monsters from the Id", description: "Early experimental electronica composed 1985 by Barry Ferrier.", youtubeId: "X_1n8AHg4GQ", category: "electronic", featured: false, order: 28 },
    { title: "Expo 88 Light Fantastic Parade", description: "QANTAS \"Light Fantastic Parade\" experimental electronica by Barry Ferrier for Brisbane World Expo 88.", youtubeId: "k2-OTVly07M", category: "electronic", featured: false, order: 29 },
    { title: "Lindsay Kemp Company: Salomé", description: "Excerpts from Salomé at The Roundhouse London 70s featuring music by Andrew Thomas Wilson and Barry Ferrier.", youtubeId: "cCwwzQreNuU", category: "electronic", featured: false, order: 30 },
    { title: "The Empire's Finally Falling", description: "The Empire's Finally Falling - Dr Baz", youtubeId: "pi2gWCVNNAs", category: "hip-hop", featured: false, order: 30 },
    { title: "There Must Be a Plan", description: "\"There Must Be a Plan\" - Dr Baz", youtubeId: "7tQEMUttEuM", category: "hip-hop", featured: false, order: 31 },
    { title: "Cyborg in the Sunset", description: null, youtubeId: "DGwOPXA742w", category: "sci-fi", featured: false, order: 31 },
    { title: "Tunnel of Love", description: "Tunnel of Love - Dr Baz", youtubeId: "ioaNIfUn-PQ", category: "hip-hop", featured: false, order: 32 },
    { title: "Time Travellers", description: null, youtubeId: "yvZFn7QVJeU", category: "sci-fi", featured: false, order: 32 },
    { title: "Weapons of Mass Distraction", description: null, youtubeId: "EAw4J1mK6S8", category: "sci-fi", featured: false, order: 33 },
    { title: "Party Animal", description: "Party Animal - Dr Baz", youtubeId: "Gae4VRhS1Xw", category: "hip-hop", featured: false, order: 33 },
    { title: "Futuristic Days - Dr Baz", description: null, youtubeId: "zhE1eCCr8G0", category: "sci-fi", featured: false, order: 34 },
    { title: "Cogito Ergo Sum", description: "AI sci-fi short film exploring consciousness and Descartes' philosophy - \"I think, therefore I am.\" A Barry Ferrier Film.", youtubeId: "qiD4gLQFhvE", category: "sci-fi", featured: false, order: 35 },
    { title: "Ascension", description: "AI robots are coming. Are you ready? A sci-fi short film exploring the rise of artificial intelligence. A Barry Ferrier Film.", youtubeId: "ca5C40r0B70", category: "sci-fi", featured: false, order: 36 },
    { title: "The Sea Remembers", description: "Winner \"Best Environmental Film\" New York Shorts Film Festival, \"Best Animation\" Cannes Arts Film Festival, Shanghai & Hong Kong Indie Film Festivals. A musical call to action against ocean plastic pollution.", youtubeId: "QRXOBAuXf5E", category: "environmental", featured: false, order: 37 },
    { title: "The Lament of the Whales", description: "An environmental documentary exploring the crisis facing humpback whales - from ocean noise pollution to ecosystem collapse. Music and video by Dr Baz.", youtubeId: "TjfqFWV3iUk", category: "environmental", featured: false, order: 38 },
    { title: "Wild and Free", description: "A heartfelt lament for nature and biodiversity loss. Since the 70s we have lost 70% of biodiversity on this planet. Song and video by Dr Baz.", youtubeId: "R5PZsxiq7N4", category: "environmental", featured: false, order: 39 },
    { title: "Love Your Planet", description: "A musical tribute to Earth - our irreplaceable home. Lyrics by Ralph Lycett Tyrrell, music composed and performed by Barry Ferrier aka Dr Baz.", youtubeId: "ueuaNm9VL4Q", category: "environmental", featured: false, order: 40 },
    { title: "2 Headz R Better Than 1 (Part 1)", description: "Animated cartoon starring Boof & Dick Head - roadies on a strange trip to the Real Reality where they meet Steven Seagull. Animation by Barry Ferrier, dialogue by Ian Mason (circa 1999).", youtubeId: "5AJUZj8xww4", category: "cartoons", featured: false, order: 41 },
    { title: "2 Headz R Better Than 1 (Part 2)", description: "Part 2 of the animated cartoon starring Boof & Dick Head. The Flamingo Lounge - a surreal den of iniquity controlled by the evil Madame Magdalena. Animation by Barry Ferrier.", youtubeId: "UL2lbMgO6Es", category: "cartoons", featured: false, order: 42 },
    { title: "I Get Bored Easily", description: "Animated music video from the retro swing jazz album \"Stay Classy\". Lyrics by Ralph Lycett Tyrrell, music and video by Dr Baz.", youtubeId: "tSTLVlCZ938", category: "cartoons", featured: false, order: 43 },
    { title: "Stay Classy", description: "Animated music video from the S'uNReel retro swing jazz album \"Stay Classy\". Lyrics by Ralph Lycett Tyrrell, music and video by Dr Baz.", youtubeId: "THyRVlOfxkg", category: "cartoons", featured: false, order: 44 },
    { title: "Crazy Demon", description: "Original animated music video. Song composed by Dr Baz & EMU. All instruments and vocals by Barry Ferrier, drums by Rick Brewer.", youtubeId: "ZzclMtn_R2k", category: "cartoons", featured: false, order: 45 },
    { title: "The Open Door", description: "Animated film with haunting piano improvisation by virtuoso Fred Cole. An enigmatic cartoon by Doctor Baz exploring what lies behind the open door.", youtubeId: "AqnYql91NLc", category: "cartoons", featured: false, order: 46 }
  ];

  const existingVideos = await db.select().from(videos);
  const seedTitles = new Set(allVideos.map(v => v.title));
  const staleVideos = existingVideos.filter(v => !seedTitles.has(v.title));
  for (const stale of staleVideos) {
    await db.delete(videos).where(eq(videos.id, stale.id));
    console.log(`Removed stale video: "${stale.title}" (${stale.youtubeId})`);
  }
  const existingIds = new Set(existingVideos.map(v => v.youtubeId + ':' + v.title));
  const newVideos = allVideos.filter(v => !existingIds.has(v.youtubeId + ':' + v.title));
  if (newVideos.length > 0) {
    await db.insert(videos).values(newVideos);
  }
  console.log("Videos synced");

  const existingSlides = await db.select().from(slides);
  if (existingSlides.length === 0) {
    await db.insert(slides).values([
      { headline: "Musician", content: "Born in Sydney, Australia, Barry gained early recognition in music theatre, appearing in Jesus Christ Superstar in Sydney and Melbourne, then in Joseph & the Amazing Technicolour Dreamcoat at the Seymour Centre, Sydney.", ctaText: "Learn More", ctaLink: "/history", order: 0 },
      { headline: "Entertainer", content: "Described as 'the Charles Bronson of swamp blues' by someone who ought to know better, Barry has fascinating music industry credits and stars in his self-penned theatre show on the life of Johnny Cash.", ctaText: "See Projects", ctaLink: "/projects", order: 1 },
      { headline: "Designer", content: "He's 'the doctor' because he's earned a PhD in multimedia design. With over 200 websites designed, Barry brings technical excellence to creative projects.", ctaText: "View Services", ctaLink: "/about", order: 2 },
      { headline: "Byron Bay Legend", content: "As a long-time resident of the Byron Bay region, Barry established himself as a pioneer of the local music scene in the early 80s, becoming a beloved entertainer for over four decades.", ctaText: "Discover History", ctaLink: "/history", order: 3 },
    ]);
  }

  const allImages = [
    { name: "QPAC Concert Hall", category: "electronic", objectPath: "https://barryferrier.com/media/k2/galleries/16/Queensland-Performing-Arts-Centre.jpg", altText: "Queensland Performing Arts Centre", order: 0 },
    { name: "Dreams & Machines Programme", category: "electronic", objectPath: "https://barryferrier.com/images/com_osgallery/gal-12/original/dreams-machines-programme-front-cover2D648A67-2E42-8CA8-847C-D4B73C5F46E5.jpg", altText: "Dreams & Machines programme front cover", order: 0 },
    { name: "Dreams & Machines Media", category: "electronic", objectPath: "https://barryferrier.com/images/com_osgallery/gal-12/original/dreams-machines-media-24FEB32FB-A44C-F41E-1846-A7F670A05A7C.jpg", altText: "Dreams & Machines media coverage", order: 0 },
    { name: "Fairlight CMI", category: "electronic", objectPath: "https://barryferrier.com/media/k2/galleries/16/fairlightcmi.jpg", altText: "Fairlight CMI Computer Musical Instrument", order: 0 },
    { name: "Barry Ferrier 2017", category: "headshots", objectPath: "https://barryferrier.com/images/Barry-Ferrier-2017.jpg", altText: "Barry Ferrier 2017", order: 0 },
    { name: "Barry Ferrier 2015", category: "headshots", objectPath: "https://barryferrier.com/images/Barry-Ferrier-2015.jpg", altText: "Australian musician Barry Ferrier aka Dr. Baz", order: 0 },
    { name: "Barry Ferrier 2018", category: "headshots", objectPath: "https://barryferrier.com/images/Barry-Ferrier-2018.jpg", altText: "Australian musician Barry Ferrier aka Dr. Baz", order: 0 },
    { name: "Johnny Cash Tribute", category: "johnny-cash", objectPath: "https://barryferrier.com/images/Doctor-baz/2/Barry-Ferrier-Johnny-Cash.jpg", altText: "Barry Ferrier as Johnny Cash", order: 0 },
    { name: "Pete C & Dr Baz", category: "pete-c", objectPath: "https://barryferrier.com/images/Pete_C__Dr_Baz_sm.jpg", altText: "Pete C & Dr Baz Blues Duo, Byron Bay", order: 0 },
    { name: "Slider Image 2", category: "slider", objectPath: "https://barryferrier.com/images/slideshow/Barry_Ferrier-1.jpg", altText: "Barry Ferrier live performance", order: 0 },
    { name: "Slider Image 1", category: "slider", objectPath: "https://barryferrier.com/images/slideshow/Barry_Ferrier-7.jpg", altText: "Barry Ferrier performing", order: 0 },
    { name: "Doctor Baz Solo", category: "solo", objectPath: "https://barryferrier.com/images/Doctor-baz/2/Doctor-Baz-Solo.jpg", altText: "Doctor Baz aka Barry Ferrier performing solo", order: 0 },
    { name: "Barry Ferrier Solo", category: "solo", objectPath: "/attached_assets/Barry_Ferrier_1770262968741.jpg", altText: "Barry Ferrier - Doctor Baz Solo Performer", order: 0 },
    { name: "Baz in Bangalow", category: "solo", objectPath: "/attached_assets/Baz_in_Bangalow_1770263019441.jpg", altText: "Doctor Baz in Bangalow", order: 0 },
    { name: "Ralph Lycett Tyrrell", category: "sunreel", objectPath: "/attached_assets/Ralph_1770263091345.jpeg", altText: "Ralph Lycett Tyrrell - S'uNReel collaborator", order: 0 },
    { name: "S'uNReel Entertainment", category: "sunreel", objectPath: "/attached_assets/S'uNReel_Entertainment_1770263299263.jpg", altText: "S'uNReel Entertainment - Dr Baz and Ralph Lycett Tyrrell", order: 0 }
  ];

  const existingImages = await db.select().from(images);
  if (existingImages.length < allImages.length) {
    const existingPaths = new Set(existingImages.map(i => i.objectPath));
    const newImages = allImages.filter(i => !existingPaths.has(i.objectPath));
    if (newImages.length > 0) {
      await db.insert(images).values(newImages);
    }
  }
  console.log("Images synced");

  console.log("Database sync completed!");
}
